content = open('server/support_environment.py', 'r', encoding='utf-8').read()
content = content.replace('\tdef get_metadata', '    def get_metadata')
content = content.replace('\t        from openenv', '        from openenv')
content = content.replace('\t        return EnvironmentMetadata', '        return EnvironmentMetadata')
content = content.replace('\t            name=', '            name=')
content = content.replace('\t            description=', '            description=')
content = content.replace('\t            version=', '            version=')
content = content.replace('\t            author=', '            author=')
content = content.replace('\t            documentation_url=', '            documentation_url=')
content = content.replace('\t        )', '        )')
open('server/support_environment.py', 'w', encoding='utf-8').write(content)
print('Done!')