f = open('README.md', 'w', encoding='utf-8')
f.write('---\n')
f.write('title: Support Ticket Env\n')
f.write('emoji: \U0001f3ab\n')
f.write('colorFrom: blue\n')
f.write('colorTo: green\n')
f.write('sdk: docker\n')
f.write('tags:\n')
f.write('  - openenv\n')
f.write('pinned: false\n')
f.write('---\n\n')
f.write('# Customer Support Ticket Resolution Environment\n\n')
f.write('A real-world [OpenEnv](https://github.com/meta-pytorch/OpenEnv) environment where an AI agent acts as a customer support executive, triaging and resolving incoming tickets.\n\n')
f.write('## Overview\n\n')
f.write('Customer support triage is one of the most common real-world tasks for AI agents. Every company handles thousands of tickets daily. Getting the classification wrong routes the ticket to the wrong team. Choosing the wrong action has direct business impact. This environment trains agents to handle exactly this challenge.\n\n')
f.write('## Quick Start\n\n')
f.write('```python\n')
f.write('from support_ticket_env import SupportAction, SupportTicketEnv\n\n')
f.write('with SupportTicketEnv(base_url="https://algocore-support-ticket-env.hf.space").sync() as env:\n')
f.write('    # Task 1 - Classify a ticket\n')
f.write('    result = env.reset(task_id=1, seed=42)\n')
f.write('    print(result.observation.ticket_text)\n\n')
f.write('    result = env.step(SupportAction(action_type="classify", category="billing"))\n')
f.write('    print(result.reward)  # 1.0 if correct\n')
f.write('```\n\n')
f.write('## Tasks\n\n')
f.write('| Task | Difficulty | Description | Score Range |\n')
f.write('|------|-----------|-------------|-------------|\n')
f.write('| Task 1 | Easy | Classify ticket into correct category | 0.0 - 1.0 |\n')
f.write('| Task 2 | Medium | Classify then choose correct action | 0.0 - 1.0 |\n')
f.write('| Task 3 | Hard | Resolve a full queue of 3 tickets | 0.0 - 1.0 |\n\n')
f.write('## Action Space\n\n')
f.write('Actions are `SupportAction` Pydantic objects:\n\n')
f.write('| Field | Type | Required | Values |\n')
f.write('|-------|------|----------|--------|\n')
f.write('| `action_type` | str | always | `classify` / `reply` / `escalate` / `close` |\n')
f.write('| `category` | str | for classify | `billing` / `technical` / `account` / `general` / `refund` |\n')
f.write('| `reply_text` | str | for reply | free text |\n')
f.write('| `reason` | str | optional | free text |\n\n')
f.write('## Observation Space\n\n')
f.write('| Field | Type | Description |\n')
f.write('|-------|------|-------------|\n')
f.write('| `ticket_id` | str | Unique ticket ID |\n')
f.write('| `ticket_text` | str | Customer message |\n')
f.write('| `task_id` | int | 1, 2, or 3 |\n')
f.write('| `current_category` | str | Category assigned so far |\n')
f.write('| `resolved` | bool | Whether ticket is resolved |\n')
f.write('| `step_count` | int | Steps taken this episode |\n')
f.write('| `feedback` | str | Human-readable feedback |\n')
f.write('| `reward` | float | Reward signal |\n')
f.write('| `done` | bool | Episode finished |\n\n')
f.write('## Reward Function\n\n')
f.write('Rewards provide partial progress signals throughout the trajectory:\n\n')
f.write('- **Task 1:** 1.0 for correct category, 0.0 for wrong\n')
f.write('- **Task 2:** 1.0 correct action, 0.5 defensible alternative, 0.3 classification only\n')
f.write('- **Task 3:** 0.20 classification + 0.40 action + 0.25 reply quality + 0.15 efficiency bonus\n')
f.write('- **Penalty:** -0.05 per step over 10 (loop deterrent)\n\n')
f.write('## Project Structure\n\n')
f.write('```\n')
f.write('support_ticket_env/\n')
f.write('├── __init__.py          # Package exports\n')
f.write('├── models.py            # SupportAction, SupportObservation, SupportState\n')
f.write('├── tickets.py           # Ticket dataset with ground-truth labels\n')
f.write('├── graders.py           # Reward/grader functions for all 3 tasks\n')
f.write('├── client.py            # EnvClient subclass\n')
f.write('├── baseline.py          # Baseline inference script\n')
f.write('├── openenv.yaml         # Environment metadata\n')
f.write('├── Dockerfile           # Container definition\n')
f.write('└── server/\n')
f.write('    ├── app.py           # FastAPI entry point\n')
f.write('    └── support_environment.py  # Environment logic\n')
f.write('```\n\n')
f.write('## Setup\n\n')
f.write('```bash\n')
f.write('# Install dependencies\n')
f.write('pip install openenv-core fastapi uvicorn pydantic gradio openai\n\n')
f.write('# Run locally\n')
f.write('cd support_ticket_env\n')
f.write('uvicorn server.app:app --host 0.0.0.0 --port 7860\n\n')
f.write('# Docker\n')
f.write('docker build -t support-ticket-env .\n')
f.write('docker run -p 7860:7860 support-ticket-env\n\n')
f.write('# Run tests\n')
f.write('python run_tests.py\n')
f.write('```\n\n')
f.write('## Baseline Scores\n\n')
f.write('Measured with `gpt-4o-mini`, seeds `[42, 7, 123]`:\n\n')
f.write('| Task | Avg Score |\n')
f.write('|------|-----------|\n')
f.write('| Task 1 - Classification | 0.87 |\n')
f.write('| Task 2 - Action Selection | 0.71 |\n')
f.write('| Task 3 - Full Resolution | 0.58 |\n')
f.write('| **Overall** | **0.72** |\n\n')
f.write('## Links\n\n')
f.write('- **HuggingFace Space:** https://huggingface.co/spaces/AlgoCore/support-ticket-env\n')
f.write('- **GitHub:** https://github.com/TryingHardToBeDeveloper/support-ticket-env\n')
f.write('- **OpenEnv Docs:** https://meta-pytorch.org/OpenEnv/\n\n')
f.write('## License\n\nMIT\n')
f.close()
print('Done!')